language: ruby
rvm:
 - 2.2
 - jruby
 os: osx

script: "rake"

osx_image: xcode11.0
env:
  matrix:
    - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone 11 Pro'
    - TEST_SDK=iphonesimulator13.0 OS=13.0 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project BlueSwiftLib.xcodeproj -scheme BlueSwiftLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
